-----------------------------------------------------------------------------
-- Hivemall: Hive scalable Machine Learning Library
--
-- Copyright (C) 2013-2014
-- National Institute of Advanced Industrial Science and Technology (AIST)
-- Registration Number: H25PRO-1520
-----------------------------------------------------------------------------

---------------------------------
-- Dataset generator functions --
---------------------------------

drop temporary function lr_datagen;
create temporary function lr_datagen as 'hivemall.dataset.LogisticRegressionDataGeneratorUDTF';
