-----------------------------------------------------------------------------
-- Hivemall: Hive scalable Machine Learning Library
--
-- Copyright (C) 2014
-- National Institute of Advanced Industrial Science and Technology (AIST)
-- Registration Number: H25PRO-1520
-----------------------------------------------------------------------------

--------------------------
-- Matrix Factorization --
--------------------------

drop temporary function mf_predict;
create temporary function mf_predict as 'hivemall.mf.MFPredictionUDF';

drop temporary function train_mf_sgd;
create temporary function train_mf_sgd as 'hivemall.mf.MatrixFactorizationSGDUDTF';

drop temporary function train_mf_adagrad;
create temporary function train_mf_adagrad as 'hivemall.mf.MatrixFactorizationAdaGradUDTF';



